<a href="https://colab.research.google.com/github/ShigekiKamata/Learn/blob/main/TensorFlow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

import tensorflow as tf

In [ ]:
tf.__version__

'2.17.0'

In [ ]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(7654, 4)
(7654,)
(1914, 4)
(1914,)


In [ ]:
# ANN skelton
ann = tf.keras.models.Sequential()

# 1st hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# 2nd hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Last layer (regression)
ann.add(tf.keras.layers.Dense(units=1, activation=None))

# Compile the ANN, optimizer specifies the way of stocastic gradient descent
ann.compile(optimizer='adam', loss ='mean_squared_error')

In [ ]:
# Train model
# epoch: one run through of dataset
# batch_size: size of each subset of dataset when it's devided
# Iteration: run through of a batch, one weight update happens per iteration
# During an iteration, gradients (from ) get averaged for one average gradient fot the batch

ann.fit(X_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 826825.0000
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 39150.4102
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 339.1690
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 260.1105
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 255.5991
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 255.8943
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 240.7281
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 232.5500
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 223.7296
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 213.0677
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 204.2482
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 185.3141
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 170.9517
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 156.7503
Epoch 15/1

In [ ]:
y_test.shape

(1914,)

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), axis=1)


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([[431.43, 431.23],
       [462.39, 460.01],
       [465.87, 461.14],
       ...,
       [473.11, 473.26],
       [439.91, 438.  ],
       [459.1 , 463.28]])